version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:22.04
   resource_class: large
   steps:
      - run:
          no_output_timeout: 50m
          command: |
            apt update && apt upgrade -y
            apt install bc build-essential bison flex zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd openjdk-11-jdk openjdk-11-jre python-is-python3 -y
            git clone https://github.com/Ancient-Project/android_kernel_xiaomi_violet.git -b rebase3 --depth=1 violet
            cd violet
            bash build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
